### ISSUE TITLE
Request Data

### ISSUE THREAD

**Issue by Peregalli** [stu9113611/RLMD#1]
Hi! 

Note that they are still working on the git repository. I tried to access the link to download the data ([this one](https://ccu365-my.sharepoint.com/_forms/default.aspx)), but I think I don't have permission (or it's still not enabled for everyone to see it). I would like to take a look, my email is adiaz@digitalsense.ai

Thank you for your response!

**Comment by stu9113611** [comment]
Hi Peregalli

Thank you for letting us know the download link was expired! The link was updated, please give it another try.
Feel free to ask anything if you have difficulties using the dataset.

**Comment by Peregalli** [comment]
Excellent! Thanks!
